### ISSUE TITLE
Shallows A and E look the same.

### ISSUE THREAD

**Issue by ThePenitence** [MoshirMoshir/BlueMaps#1]
The maps for Shallows A and E look identical as though it was an accidental copy or something. There is some very slight difference between the two but only in texture of the walls and one extra block in the corner, they are otherwise the exact same level shape. I noticed you are also missing the Shallows Seaweed version which spawn Sheepshead and Catfish, so maybe that's what should be in the E slot?

**Comment by MoshirMoshir** [comment]
Wow! Good Catch! From my understanding, Map A is actually the tutorial one, which apparently is separate from the normal Maps. I think in this case it's fine to remove it. I'll update the map and resolve this issue once I finish.

In regards to Shallows Seaweed, I believe that is Map F (I removed the seaweed since the texture breaks after datamining). I was planning maybe to add labels later, but the seaweed (to my current knowledge) only can spawn with that map shape anyways.

**Comment by ThePenitence** [comment]
Ah it was a tutorial map, makes sense they'd have a separate static one for such case. You only get to see it once so I wouldn't have thought of that! I'm not sure about F being the seaweed map, when I was going over this the day I wrote it I was in a seaweed map and I was trying to figure out the layout compared to your map and it just didn't seem to line up to me. But maybe I was wrong. If I ever go there again I'll triple check. 

Appreciate the update btw! The escape pod points add such a great sense of location, can easily tell the map shape just by finding one of them. Also really appreciate sewing all the maps into one modular shape. I would actually prefer using the mobile version page because I liked the vertical map to connect them as it were in game.

**Comment by MoshirMoshir** [comment]
Heck yeah!

I am pretty happy with the update, def had a real long hiatus cause of IRL busyness. But finally got around to putting in some work and the current map had always been my intention. I finally achieved it so glad you like it as well!
Hoping to add more overlays but things like sharks and items are alot harder; I have to manually go in game and mark each object down since there isn't an easy way to identify it from the datamined assets (at least not that I know of).

Please let me know if the seaweed map is actually different. I'm going by the files I datamined and those were all the ones I found that would be "shallows" (they just label them scenes A, B, and C) So I could have missed a folder of specific seaweed scenes, but I was under the impression that those were all the maps they had.

**Comment by ThePenitence** [comment]
So I found the seaweed shallow and checked again and the geometry is definitely the same, just really gives a different feel of space without all the seaweed around. 

On another note it appears there are extra shallows maps for the Dredge content. There are 3 named locations you can choose to visit: Fog Coast, Black Cliff, and Jellyfish Basin. Fog Coast seemed pretty similar to ShallowsB or E I think, but Cliff was very different from any of them even having a unique brown texture to the terrain. Haven't seen the other yet. The med depths are just the same as the night time version of MediumD that's always used.

**Comment by MoshirMoshir** [comment]
Hm, good to know, I haven't actually played in a long time since I'm too busy. I'll have to see at some point if I can manually add all the seaweed back. For the other maps like the glacier area and the new dredge ones, I'll see if I can find them; they should be somewhere in the files I datamined. I'll probably eventually just add a new page for each respectively.
